version: 0.0
os: linux
files:
  - source: /
    destination: /timeoff-management-application/
hooks:
  ApplicationStop:
    - location: scripts/application_stop
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start
      timeout: 300
      runas: root


