version: 0.2

phases:
  install:
    commands:
      - echo Install Phase
      - export LC_ALL=en_US.UTF-8
      - export LANG=en_US.UTF-8
      - yum update -y
      - yum install -y git gcc-c++ make
      - curl -sL https://rpm.nodesource.com/setup_12.x | bash -
      - yum install -y nodejs
      - echo Install Phase Finished
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - USE_CHROME=1 npm test