#!/bin/bash
# vars
project_location="/home/ec2-user/timeoff-management-application"

# creating cache and log folders
cd $project_location

# starting services
sudo npm install
sudo pm2 --name TimeOffApplication start npm -- start
